### ISSUE TITLE
long time to run

### ISSUE THREAD

**Issue by ramdhan1989** [akwasigroch/Pretext-Invariant-Representations#4]
Hi,
I just want to make sure, has the code been tested successfully using GPU ? although it is already stated to use device = torch.device('cuda:0'), it took very long time to run (13 hours per epoch for 600k images batch size 512, I set num_workers to 0 in dataloader) . do you have any suggestions to solve run time problem ?

thank you

**Comment by akwasigroch** [comment]
My training took 1.25 min per epoch (2000 images, 224x224px) on a single GPU (GeForce 1080Ti), so on my hardware, it should take 6.25h when trained on 600k images. That’s almost half as much as your case. Data augmentation can slow down the training. Do you fully utilize the CPU?

**Comment by ramdhan1989** [comment]
Hi @akwasigroch ,
To increase CPU, do I need to increase num_workers in DataLoader like this ?
train_loader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=batch_size, num_workers=2)
I tried to put number greater than 0 but it turns out an error below : 


```
Saving representations to memory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\R\Pretext-Invariant-Representations\jigsaw.py", line 127, in <module>
    memory.initialize(net, train_loader)
  File "D:\R\Pretext-Invariant-Representations\utils.py", line 221, in initialize
    for step, batch in enumerate(train_loader):
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "jigsaw.py", line 127, in <module>
    memory.initialize(net, train_loader)
  File "D:\R\Pretext-Invariant-Representations\utils.py", line 221, in initialize
    for step, batch in enumerate(train_loader):
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

any idea ?

thank you

**Comment by ramdhan1989** [comment]
Hi @akwasigroch , I increased num_workers to 5 in dataloader but it is still slow~ 13h per epoch. IMHO, for some reason I checked my GPU performance seems it doesn't work while GPU run successfully using other scripts.  Any idea?
